### ISSUE TITLE
Can't open dmn file V1.0

### ISSUE THREAD

**Issue by steff138** [bpmn-io/dmn-js#130]
Please add a downward compatibility!
I can't open my dmn file any more - it prompts an error:

`unparsable content <decision> detected
    line: 2
    column: 53
    nested error: unrecognized element <decision>`

The file starts with 

`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/DMN/20151101/dmn11.xsd" id="definitions" name="definitions" namespace="http://camunda.org/schema/1.0/dmn">
  <decision id="valueMapping" name="Value">`

**Comment by SebastianStamm** [comment]
Please make sure that all your dependencies are up to date by removing the `node_modules` folder and running `npm install`. Especially check that you are using dmn-moddle in version 0.5.0.

**Comment by steff138** [comment]
I'm sorry - I mean I can't open my file in the online version: http://demo.bpmn.io/dmn

**Comment by ricardomatias** [comment]
The problem here is related to the namespace.

You have to change to the new namespace of DMN 1.1:

xmlns="http://www.omg.org/spec/DMN/20151101/dmn11.xsd" to xmlns="http://www.omg.org/spec/DMN/20151101/dmn.xsd"

If you don't want to do this manually, you can always try the [Camunda Modeler](https://github.com/camunda/camunda-modeler), which has a migration strategy.

We might add this migration to the demo app, but I can't estimate when.

**Comment by SebastianStamm** [comment]
In the upcoming release we add backwards-compatibility to the old namespace. See #156
