### ISSUE TITLE
 DMN In case of undo - redo subscribed events not firing

### ISSUE THREAD

**Issue by romero83** [bpmn-io/dmn-js#166]
Hi,

If I subscribe for example on DMN tableName.editId event and make custom functionality:

eventBus.on('tableName.editId', function(e) { window.alert('test') });

The custom window.alert functionality is not firing in case of undo - redo commandStack after changed the table ID and try to undo by pressing CTRL+Z.

Is it a bug or an expected output?

I think it is a bug.

Thank you,
Best regards,
Rómeó Nagy

**Comment by SebastianStamm** [comment]
This is expected behavior.

To react to redo- and undo-changes, you would use a CommandInterceptor and add your listener to the executed and reverted handlers. Take a look at the [TableUpdater](https://github.com/bpmn-io/dmn-js/blob/master/lib/table/features/modeling/TableUpdater.js) or [DRDUpdater](https://github.com/bpmn-io/dmn-js/blob/master/lib/features/modeling/DrdUpdater.js) for an example.

**Comment by romero83** [comment]
Thank you!
Just example code how to achieve this:
```
// Will execute also in case of execution and redo command at table ID change.
dmnModeler.get("tableUpdater").executed(['id.edit'], function() {
      window.alert("id edit executed");
});

// Will execute in case of undo command at table ID change.
dmnModeler.get("tableUpdater").reverted(['id.edit'], function() {
      window.alert("id edit reverted");
});
```
