### ISSUE TITLE
I can use typeahead for allowed values

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/dmn-js#25]
AT:
- When editing a cell for a clause with datatype string and allowed values, I see possible options when clicking in the cell
- While typing, only matching options are displayed
- When only one option remains, it is added to the cell in a typeahead behavior

Migrated from: https://app.camunda.com/jira/browse/CAM-4081

**Comment by SebastianStamm** [comment]
DMN 1.1 changed the way allowed values work. Instead of a list of strings, it is now an expression which is evaluated for input values (so you can write something like "number is between 10 and 150" or "string must end in -ing"). Therefore, it might not always be possible to determine the correct typeahead.

**Comment by nikku** [comment]
We'll not support typing ahead for allowed values any time soon due to the constraints @SebastianStamm mentioned. Some day maybe we could support this properly via https://github.com/bpmn-io/dmn-js/issues/280.
