### ISSUE TITLE
I can simple edit date

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#282]
Related to #243

**Comment by nikku** [comment]
Review:

* Usability: Type date in output column as specified in pattern (with `'T'` and it is invalid)
  
  ![image](https://user-images.githubusercontent.com/58601/35485746-07811628-0464-11e8-87b8-da843d111610.png)
  
  (Also: Wording; why not use `matching pattern` or `corresponding to` instead of `meaning`. I'd add a `.` in the end to finish the sentence, too.

* Question: What is the primary action for the dialog, editing the date or setting it to `today`? If it is setting to today, leave it as it is; otherwise swap input and button.

**Comment by philippfromme** [comment]
Thanks, the last one about 'between' not being recognized I can't reproduce. The other things sound reasonable to me.

**Comment by nikku** [comment]
Did you apply changes?

**Comment by nikku** [comment]
Regarding the last bug, here is a screencast: 

![bug](https://user-images.githubusercontent.com/58601/35519377-54620e60-0514-11e8-843d-2bf291181d4a.gif)

**Comment by philippfromme** [comment]
My changes: https://github.com/bpmn-io/dmn-js/commit/4b04f343c4dbc6b33c3dbe5a13760e8f6ce56467

Okay, now I know, what you mean, it doesn't work when the dates are empty, I'll have a look at that tomorrow.
