### ISSUE TITLE
Inferno warning in browser console when developing

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/dmn-js#391]
__Describe the Bug__

I am using create-react-app for my project. I installed dmn-js via yarn and use it via `import Viewer from "dmn-js";` When developing the App, in the Chrome browser console there is a warning "You are running production build of Inferno in development mode. Use dev:module entry point." When building for production (via `yarn build` in create-react-app) the error does not appear.

__Steps to Reproduce__

1. create a new create-react-app project with `create-react-app my-app`
2. `cd my-app`
3. `yarn add dmn-js`
4. Add `import Viewer from "dmn-js";` in `/src/App.js`
5. `yarn start`
6. A browser tab should open with your app, open the browser console
7. Notice the warning "You are running production build of Inferno in development mode. Use dev:module entry point. `index.esm.js:4`"

__Expected Behavior__

No warning shows up.

__Environment__

 - Browser: Chrome 72
 - OS: Linux
 - Library version: 6.2.0

**Comment by nikku** [comment]
Solution approach:

* require extension developers to use a packaged version of inferno, e.g. `dmn-js/vendor/inferno` instead of the actual package
* properly include _DEV_ or _PROD_ inferno based on the process.env.NODE_ENV environment variable

**Comment by nikku** [comment]
There is not way to workaround the warning being displayed other than telling webpack to consider the `dev:module` entry point. This is due to the nature of `esm` and the fact that we cannot conditionally include a module. 

For vanilla webpack projects, add the `dev:module` entry point like this:

```javascript
// webpack.config.js
module.exports = {
  ...,
  resolve: {
    mainFields: [ 'browser', 'dev:module', 'module', 'main' ]
  }
};
```

Users of `create-react-app` or other boilerplate projects may not configure this and must, unfortunately, live with the warning.
