### ISSUE TITLE
Add ability to resize decision table columns

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/dmn-js#500]
__Is your feature request related to a problem? Please describe.__

Currently, decision table headers can not be resized. Our new [decision table layout](https://dmn-prototypes.netlify.app/column-editing-final/) should introduce that ability.

__Describe the solution you'd like__

Make input/output / (annotation) columns resizable (horizontally)

![Kapture 2020-04-15 at 13 21 57](https://user-images.githubusercontent.com/9433996/79538959-a5452800-8085-11ea-9fc5-c8244b109c66.gif)

Things to consider:

Introducing with the new column header layout (cf. #499) labels will have a max-width and can be cropped. Resizing the column width should follow this guideline in cropping, but it should be possible to give columns a custom width. This can potentially be stored inside the XML as extension property since the DMN standard does not have something like this.

__Describe alternatives you've considered__

/

__Additional context__

Child of #494 

__Acceptance criteria__

- [x] input/output columns can be resized and content is cropped
- [x] hit policy hints are moved to `title` property
- [x] logo is moved (visually) inside the decision properties
- [x] cells' content is wrapped
- [x] annotations column can be resized
- [x] table keeps correct layout on minimum width
- [x] clauses are not visible on header cell hover
- [x] drag'n'drop handle is moved to the left
- [x] column width is saved in the XML

**Comment by barmac** [comment]
We want the width to be saved (extension properties will help).

**Comment by barmac** [comment]
Should the content of the entries be cropped like we do with the label? What should happen to the layout of the table when you start editing the rule?

I think it could behave in a similar way as input/output editing, i.e. the entry cell should "emerge" from the table so that it does not affect table layout.

**Comment by pinussilvestrus** [comment]
So basically what we come up with [in this thread](https://github.com/camunda/camunda-modeler/issues/117#issuecomment-638227634), am I right? Would agree with it, makes a lot of sense

**Comment by barmac** [comment]
Correct.

**Comment by barmac** [comment]
Progress so far: I have a concept how to implement the visuals. The table row with decision name will have to be moved out from the HTML table, so that `table-layout: fixed` can handle column widths. Still, I don't intend yet to change the visuals. Then, content of the cells will be hidden in case of overflow.

**Comment by barmac** [comment]
I've added _Acceptance criteria_ to track issue status.

**Comment by barmac** [comment]
So I think this is the last problem to fix:
![image](https://user-images.githubusercontent.com/28307541/86330780-7849ef80-bc48-11ea-8454-429dc016784a.png)
