### ISSUE TITLE
EventListener for event bus on div instead of document

### ISSUE THREAD

**Issue by placsta** [bpmn-io/dmn-js#524]
__Is your feature request related to a problem? Please describe.__

The event bus registers event listener on document. For example for click.
The drop zone for dmn-js is in an panel of a custom UI framework, which stops the propagation of HMTL events and send custom events.

```html
<bm-panel onclick="event.stopPropagation();">
    <div class="editor-container"></div>
</bm-panel>
```

In this case dmn-js doesn't work correct anymore, because the event isn't received by the event bus.

Here is a small project to illustrate the problem:
https://github.com/placsta/dmn-js-eventbus-example
https://codesandbox.io/s/github/placsta/dmn-js-eventbus-example

It's not possible to work with the dmn table, when the propagation of events (in the example 'click') is stopped on a parent element.

__Describe the solution you'd like__

If the event bus of the table adds the event listener not on the document, but instead on the <div>, the event handling would still get the events and can work.

There should be a way to register the event bus on the div of the drop zone instead of document.

__Describe alternatives you've considered__

The only other solution I found, was to remove the event handler from the custom framework panels after rendering.

**Comment by nikku** [comment]
We have [an issue template](https://github.com/bpmn-io/dmn-js/issues/new/choose), please update your issue according to it.

If you're proposing a feature based on a real world use-case, please provide us with that real world use case in a [CodeSandBox](https://codesandbox.io).

We cannot help you, otherwise.

**Comment by placsta** [comment]
Hi @nikku 

I added an example, that shows the problem and a few more information. Do you need more information?

**Comment by barmac** [comment]
Thank you for the repo with the example. I think I get correctly what your issue is about.

So the problem is that when you stop event propagation in any DOM nodes containing the container to which `dmn-js` is attached, click event handlers within the library stop to work. As an effect, we are no longer able to view DRD from the table, open context menus etc.

Probably, if we attached listeners to the `dmn-js` container instead, the event handlers should work correctly. Unfortunately, handling events via single `document` listener is an inherent part of [`inferno-js`](https://infernojs.org/) on which we heavily depend in `dmn-js-decision-table` and `dmn-js-literal-expression`. It is rather not feasible that we change anything here soon.

Anyway, why would you call `event.stopPropagation` on all events regardless if you handle them or not? If you stop propagation only for the events that are handled by your application, there should be no problems with event handlers within `dmn-js`.

**Comment by barmac** [comment]
Alternatively, you can try out to render `dmn-js` within an `<iframe>` element. This seems to fix the issue.

Cf. https://codesandbox.io/s/goofy-swirles-uv16n?file=/src/index.html

**Comment by placsta** [comment]
Thanks for the help. An iframe isn't a solution for us. But we will find a way to listener, that stops the event propagation.
