### ISSUE TITLE
License Logo

### ISSUE THREAD

**Issue by KrishnaPG** [bpmn-io/dmn-js#573]
__Is your feature request related to a problem? Please describe.__

This is w.r.to the new logo SVG that has to be mandatorily displayed when using this package in a custom application. The displaying part is fine, but the new logo has become a source of concern. Earlier the logo used to be an image and it was fine. It gave the impression of a "powered by some brand".

The new "logo", on the contrary, is a website / domain name (bpmn.io) that is making our application look like the whole diagram was stolen from the bpmn.io and displayed on our page (something like iframe insertion), which is not a good impression nor the right one.

I can understand requiring a "powered by ...", but displaying a website domain name (bpmn.io) on the header portions of tables and everywhere else where a diagram is present, is misleading. It is giving a wrong impression.

__Describe the solution you'd like__

Something like

- "powered by Camunda" seems reasonable (it sounds like a brand and is a text, if text is what you prefer)
- or letting us display the old logo is also fine (it is easily idenfitable as a brand, and does not convey the wrong impression of stealing from some other website)

Preferred solution would be: Kindly give a choice of multiple logo styles, text styles etc. and let the developers use the most apt one for their website's theme and context.

__Describe alternatives you've considered__

Few options like flowable, kogito etc. but would prefer not to switch, if this can be resolved.

**Comment by philippfromme** [comment]
Can you elaborate on your concern that the new logo gives the impression that _the whole diagram was stolen from the bpmn.io_? I'm not sure whether I understand what you mean by that.

The new logo is used across all of our resources so, after a while, it will be recognizable.

Furthermore, keep in mind that while the bpmn.io project is maintained by Camunda it is independent. Displaying a _Powered by Camunda_ would also give the impression that there might be a Camunda BPM engine involved.

**Comment by KrishnaPG** [comment]
Thanks @philippfromme  The problem is, `bpmn.io` is a website name, not a brand name. Showing a third party website domain (bpmn.io) gives our diagrams a wrong impression that somehow the website `bpmn.io` is hosting this content and not the application itself, or somehow the website `bpmn.io` is actively involved in the content, which is incorrect. For example, Soundcloud, github gists etc.

Either you need to comeup with a valid brandname (that is not just your website name), or kindly allow your users to use a logo image (that is not just a website URL), such as your old logo.

If you really want to stick to `bpmn.io` as the display logo, then request you to allow the users to consider how that text is displayed (and not force it as an SVG). For example, we all use "powered by Leaflet" with a backlink, but they would not force a conspicuous SVG, and allow the users to write and style the attribution inline with the rest of the website.

The problem is you cannot have two conspicuous website names on the top at the header location (which is what happens when you display a diagram, say a decision table, in the main content layout, with `bpmn.io` taking the header position on the right hand side top, while the application name itself is on the lefthand side top, consution the audience)

**Comment by volkergersabeck** [comment]
Hi @KrishnaPG,

Thanks for raising this topic. I fully understand your concerns about the new bpmn.io logo and I'd like to discuss a few options that we could do.

A little background: yes, bpmn.io is the URL of the website. But at the same time it is our brand name of the libraries that we offer, which is now leading to the issue that you describe. Regarding the visual, we aligned the new logo to the new Camunda logo that was launched beginning of this year. Therefore, we had to replace the old logo of bpmn.io and cannot bring that back.

Taken from our license text:

`The source code responsible for displaying the bpmn.io project watermark that
links back to https://bpmn.io as part of rendered diagrams MUST NOT be
removed or changed. When this software is being used in a website or application,
the watermark must stay fully visible and not visually overlapped by other elements.`

Since we cannot easily adjust this license text, a short term solution needs to be aligned with this requirement. Assuming we would not find an acceptable solution and we would have to adjust the license terms, this would take some time and planning on our side to realize and might not be feasible before Q1 next year.

Options that I do see would be to:

- add further text next to the logo, e.g. a 'powered by'
- move the logo to a different position, e.g. outside of the decision table frame such that it does not appear to be part of the table itself

I tried to mock these options in the screenshots below. Please not that these are not final designs.

Do you think that one of these options would be an improvement and to some extend solve your issue? If not, please elaborate why and I'm happy to continue working with you to find a solution.

Looking forward to solve this issue together with you.
Volker

![bpmn io logo - additional text](https://user-images.githubusercontent.com/232571/93989770-9ed08000-fd8a-11ea-8595-5deab8855465.png)

![bpmn io logo - position](https://user-images.githubusercontent.com/232571/93989773-a001ad00-fd8a-11ea-93a3-02888b56f8d8.png)

**Comment by KrishnaPG** [comment]
Thank you @volkergersabeck for understanding the problem and suggesting the possible solutions.

The first proposition, "powered by bpmn.io" once again explicitly enforces the idea that somehow our current website or its content is "powered by" (as in hosted or actively supported by) the website "bpmn.io", which is not the case. So, I guess we should not consider that path. i.e. just `bpmn.io` is better without that explicit  "powered by".

The challenge is, both your website and logo are the same, hence there is always a factor of confusion when we try to add that logo to third-party applications, such as the customer applications (which are also websites), especially when the `bpmn.io` appears very close to the top menu or main navbar, where the other important business-related links will be present.

Usually, the best place for the credit attribution is at the bottom right corner of the diagrams, if that is possible. `à la leaflet`. 

I think the main DRD diagram editor currently places the logo it at the bottom-right. The `table editor`, and `single-expression editors` places this logo it at the **top right**, which will endup being near to the top menu or navbar of the app. 

- If the logo can be consistently placed at the bottom-right on all documents (or even better, allow the caller to specify the logo position when initializing the API), it should be somewhat better.

**Comment by volkergersabeck** [comment]
Thanks for your feedback, this is really helpful.

Another option that we could imagine: having the bpmn.io logo in the bottom right corner as a floating overlay, similar to the DRD view. What would be important is that the logo is not just below the decision table and would scroll outside of the viewport for large tables. Then it could look similar to the screenshot below.

Would this be a viable solution from your perspective?

If that is the case then we would discuss internally how and when we could provide this option to you.

![bpmn io logo - position](https://user-images.githubusercontent.com/232571/94030768-7b272d00-fdbe-11ea-8b11-c3fa4a61fa38.png)

**Comment by KrishnaPG** [comment]
Thank you @volkergersabeck 

I guess that would make it consistent with the DRD view. Though, I do not understand what is meant by "scroll outside of the viewport for large tables". As long as the logo does not add any extra scrollbars that would not otherwise be required, it should be fine. 

My understanding is that, if the table itself is large, then that table or some portion of it would go outside the current view - correct? To access the last rows of the table we would have to use some kind of scrolling mechanism (either on the table itself, or on its container). As long as the logo itself does not cause the scrollbar, I guess it should be fine.

**Comment by volkergersabeck** [comment]
Hi @KrishnaPG,

Thanks for confirming that this would be ok for you. And sorry if my description was not very clear, but I meant it in the way that you described.

After discussing with the team, we will include this change into the next release of dmn-js, which is due beginning of October. 

In case you have any additional feedback, please don't hesitate to let us know.
