### ISSUE TITLE
Quotation marks should not be required in string input

### ISSUE THREAD

**Issue by Kimbo0o** [bpmn-io/dmn-js#777]
__Is your feature request related to a problem? Please describe.__

I build a dmn table and wanted to test it in a process definition. So I defined a value "a" in my bpmn-js-properties-panel input. During process runtime no dmn row was selected. Later I found out that the value must not have quotation marks in the properties panel but must have quotation marks in the dmn table. This is not intuitive. 

__Describe the solution you'd like__

Quotation marks should be optional in dmn tables. This would allow users to use the same value in the input definition as in the dmn table.

**Comment by nikku** [comment]
Could you share some details (i.e. a screenshot) that establishes more context? For me it is not entirely clear what specific behavior you refer to.

**Comment by Kimbo0o** [comment]
![Screenshot 2023-09-21 115942](https://github.com/bpmn-io/dmn-js/assets/81405223/dc2ad51c-15cc-48e6-8f8b-40a766006222)
I would expect the second row to be a valid input since I defined the columns to be of type string.

**Comment by nikku** [comment]
I can understand where you are coming from. In fact an early version of our library had two modes, and did hide the `"` in _simple mode_. 

Despite the column type being `string` the value can still be a FEEL expression, i.e. `if a then "winter" else "summer"`. In order to tell apart both we need to keep the `"`. In your example `Winter` resolves to the value of a variable `Winter` :slightly_smiling_face:.

Does this make sense?

**Comment by Kimbo0o** [comment]
Yes, that makes sense. Thank you for the explanation.
