### ISSUE TITLE
DMN-JS Bundling Modeler: Inability to Edit Column Properties (Name, Expression) in Decision Tables

### ISSUE THREAD

**Issue by EricCpy** [bpmn-io/dmn-js#889]
### Describe the Bug

When creating a new Decision Table, it is not possible to fill in all column names and expression names. Additionally, after editing an expression name in an existing Decision Table, it becomes impossible to edit the column name in another Decision Table.

#### First Bug:
1. Download the [Example](https://github.com/EricCpy/DMN-JS-Bundled) (same as the [Bundling Example](https://github.com/bpmn-io/dmn-js-examples/tree/main/bundling) but using a modeler instead of a viewer).
2. Run `npm install`.
3. Run `npm run all`.
4. Create a new Decision Table.
5. Fill in the first column name and expression.
6. Attempt to fill in the second column name and expression - it doesn't work.

#### Second Bug:
1. Follow steps 1-3 as above.
2. Open an existing Decision Table and edit a column expression.
3. Open another Decision Table and try to edit a column name - it doesn't work.

### Expected Behavior

It should be possible to fill in all column names and expressions before creating the first row. Additionally, editing a column expression in one Decision Table should not prevent editing column names in other Decision Tables.

### Environment

- NodeJS: 20.15.1 (with `NODE_OPTIONS=--openssl-legacy-provider`)
- Browser:
  - Working: Firefox 128
  - Not Working: Chrome 126.0.6478.183, Microsoft Edge 126.0.2592.102
- OS: Windows 10, macOS 14
- Library version: {"dmn-js": "16.6.1"}

**Comment by barmac** [comment]
I cannot reproduce this issue. Did you double-click on the table header?

https://github.com/user-attachments/assets/c972ecaa-fe58-43ae-8661-cfad15a5a3d7

**Comment by EricCpy** [comment]
Could you please try the following steps in this order:
1. Open Decision Table
2. Fill in the column name/label
3. Fill in the column expression
4. Try to fill in the other column names

If I follow your order and fill in the expression first instead of the name, it works for me too.

**Comment by barmac** [comment]
OK I can reproduce it. Output is not editable again after the exact steps you wrote.

https://github.com/user-attachments/assets/cd6d58ea-9443-4bac-ab63-3bc4a88a093f

Can you reproduce it on https://demo.bpmn.io/dmn?

**Comment by barmac** [comment]
I cannot reproduce it on demo.bpmn.io.

**Comment by EricCpy** [comment]
No, I cannot reproduce the issue in any of your online examples.

**Comment by barmac** [comment]
Can you reproduce it when you run `npm start` in dmn-js repository? I cannot.

**Comment by EricCpy** [comment]
I cannot reproduce it when I run `npm start` in the dmn-js repository.

**Comment by barmac** [comment]
I rebuilt the bundling example with modeler, and so far this is the only setup in which I can reproduce this issue: https://github.com/bpmn-io/dmn-js-examples/pull/30

**Comment by barmac** [comment]
@jarekdanielak to have a look

**Comment by jarekdanielak** [comment]
I can reproduce the problem in [EricCpy/DMN-JS-Bundled](https://github.com/EricCpy/DMN-JS-Bundled) and https://github.com/bpmn-io/dmn-js-examples/pull/30.

**The problem occurs when you close the Context Menu when Expression field is focused.** 

In the video below, I cannot change value of `season`. Temporary workaround is to unfocus the Expression field before closing the Context Menu. That's why this bug only occurs when you edit column name first and expression second, not the other way around.

https://github.com/user-attachments/assets/bdaa3c03-d766-4917-b98d-970f1e4e4b14

----

By the way, you won't have to use `NODE_OPTIONS=--openssl-legacy-provider` if you update `webpack` to the latest version. I updated it for the `dmn-js-examples` in https://github.com/bpmn-io/dmn-js-examples/pull/31.

**Comment by jarekdanielak** [comment]
@EricCpy the issue seems to be buried somewhere in the dependencies of dmn-js. If you want to continue debugging, I can suggest to start with `ContentEditable` from [bpmn-io/dmn-js](https://github.com/bpmn-io/dmn-js) and `FeelEditor` from [bpmn-io/feel-editor](https://github.com/bpmn-io/feel-editor).

Everything works fine with the [pre-packaged version](https://github.com/bpmn-io/dmn-js-examples/blob/main/pre-packaged/README.md) of dmn-js Modeler.

I will move this issue into the backlog and leave it open in case anybody comes back with a similar problem or a solution.

**Comment by EricCpy** [comment]
Working with dmn-js 16.7.0 and Chrome version 128.0.6613.114.
